//! # Report Module
//!
//! Multi-format report generation for Oalacea Lumen.

use std::path::PathBuf;

/// Report format
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReportFormat {
    Markdown,
    Html,
    Json,
    Junit,
}

/// Report generator
pub struct ReportGenerator {
    format: ReportFormat,
}

/// Report output
#[derive(Debug, Clone)]
pub struct ReportOutput {
    pub format: ReportFormat,
    pub content: String,
    pub path: PathBuf,
}

impl ReportGenerator {
    pub fn new(format: ReportFormat) -> Self {
        Self { format }
    }

    pub fn generate(&self, data: &serde_json::Value) -> anyhow::Result<String> {
        match self.format {
            ReportFormat::Json => Ok(serde_json::to_string_pretty(data)?),
            ReportFormat::Markdown => Ok(self.generate_markdown(data)),
            ReportFormat::Html => Ok(self.generate_html(data)),
            ReportFormat::Junit => Ok(self.generate_junit(data)),
        }
    }

    fn generate_markdown(&self, _data: &serde_json::Value) -> String {
        "# Oalacea Lumen Report\n\nGenerated by Oalacea Lumen".to_string()
    }

    fn generate_html(&self, _data: &serde_json::Value) -> String {
        r#"<!DOCTYPE html>
<html>
<head><title>Oalacea Lumen Report</title></head>
<body>
<h1>Oalacea Lumen Report</h1>
<p>Generated by Oalacea Lumen</p>
</body>
</html>"#.to_string()
    }

    fn generate_junit(&self, _data: &serde_json::Value) -> String {
        r#"<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Oalacea Lumen" tests="0" failures="0" errors="0">
</testsuites>"#.to_string()
    }
}
