//! Rust test templates

use crate::{FunctionInfo, Parameter, TestCase, TestCaseType, TestGeneratorOptions, TestValue};
use lumen_core::Language;

/// Helper trait for string case conversion
trait StringCase {
    fn to_snake_case(&self) -> String;
}

impl StringCase for str {
    fn to_snake_case(&self) -> String {
        self.chars()
            .enumerate()
            .map(|(i, c)| {
                if c.is_uppercase() {
                    if i > 0 {
                        format!("_{}", c.to_lowercase().collect::<String>())
                    } else {
                        c.to_lowercase().collect()
                    }
                } else {
                    c.to_string()
                }
            })
            .collect()
    }
}

/// Generate unit test for a Rust function
pub fn generate_unit_test(function: &FunctionInfo, _options: &TestGeneratorOptions) -> String {
    let test_name = format!("test_{}", function.name.to_snake_case());

    format!(
        r#"#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn {test_name}() {{
        // TODO: Implement test
        {setup}
    }}
{additional_tests}
}}"#,
        test_name = test_name,
        setup = generate_test_setup(function),
        additional_tests = generate_additional_tests(function)
    )
}

/// Generate integration test for a Rust endpoint handler
pub fn generate_integration_test(function: &FunctionInfo) -> String {
    let test_name = format!("test_{}_integration", function.name.to_snake_case());

    format!(
        r#"#[cfg(test)]
mod integration_tests {{
    use super::*;
    // TODO: Add test setup
    // Example: use axum::test::TestSuite;
    // Example: use tower::ServiceBuilder;

    #[tokio::test]
    async fn {test_name}() {{
        // TODO: Implement integration test
        // Example:
        // let app = create_app();
        // let response = app
        //     .oneshot(Request::builder()
        //         .uri("/{}")
        //         .body(Body::empty())
        //         .unwrap())
        //     .await
        //     .unwrap();
        // assert_eq!(response.status(), StatusCode::OK);
    }}
}}"#,
        test_name = test_name
    )
}

/// Generate E2E test for a Rust application
pub fn generate_e2e_test(function: &FunctionInfo) -> String {
    let test_name = format!("test_{}_e2e", function.name.to_snake_case());

    format!(
        r#"#[cfg(test)]
mod e2e_tests {{
    use super::*;

    #[tokio::test]
    async fn {test_name}() {{
        // TODO: Implement end-to-end test
        // Example with full application startup:
        // let app = spawn_app().await;
        // let client = reqwest::Client::new();
        //
        // let response = client
        //     .get(format!("{{}}/{}", app.url(), "{}"))
        //     .send()
        //     .await
        //     .unwrap();
        // assert_eq!(response.status(), 200);
    }}
}}"#,
        test_name = test_name,
        function_name = function.name
    )
}

/// Generate test for a single function
pub fn generate_function_test(function: &FunctionInfo) -> String {
    generate_unit_test(function, &TestGeneratorOptions::default())
}

/// Generate Axum-specific E2E test
pub fn generate_axum_e2e(info: &lumen_core::ProjectInfo) -> crate::TestFile {
    let json_body = r#"{"test": "value"}"#;
    let content = format!(
        r#"//! End-to-end tests for {project}
//!
//! Generated by Lumen v{version}

use axum::
    {{body::Body, http::StatusCode, routing::get, Router}};
use serde_json::json;
use tower::ServiceBuilder;
use tower_http::trace::TraceLayer;

/// Create a test application instance
async fn create_app() -> Router {{
    // TODO: Import your actual app creation function
    Router::new()
        .route("/", get(|| async {{ "Hello, World!" }}))
}}

#[tokio::test]
async fn test_health_endpoint() {{
    let app = create_app().await;

    let response = app
        .oneshot(
            axum::http::Request::builder()
                .uri("/")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

    assert_eq!(response.status(), StatusCode::OK);
}}

#[tokio::test]
async fn test_api_response_format() {{
    let app = create_app().await;

    let response = app
        .oneshot(
            axum::http::Request::builder()
                .uri("/api/test")
                .header("content-type", "application/json")
                .body(Body::from({json_body}))
                .unwrap(),
        )
        .await
        .unwrap();

    assert_eq!(response.status(), StatusCode::OK);

    let body = hyper::body::to_bytes(response.into_body()).await.unwrap();
    let json: serde_json::Value = serde_json::from_slice(&body).unwrap();

    assert!(json.is_object());
}}
"#,
        project = info.name,
        version = env!("CARGO_PKG_VERSION"),
        json_body = json_body
    );

    crate::TestFile {
        path: std::path::PathBuf::from("tests/e2e.rs"),
        content,
        test_type: crate::TestType::E2E,
    }
}

// Helper functions

fn generate_test_setup(function: &FunctionInfo) -> String {
    let mut setup_lines = Vec::new();

    // Generate mock inputs for each parameter
    for param in &function.parameters {
        let mock_value = generate_mock_value(param);
        setup_lines.push(format!("let {} = {};", param.name, mock_value));
    }

    if setup_lines.is_empty() {
        "// Arrange".to_string()
    } else {
        format!("// Arrange\n{}", setup_lines.join("\n    "))
    }
}

fn generate_additional_tests(function: &FunctionInfo) -> String {
    let mut tests = Vec::new();

    // Happy path test
    tests.push(generate_happy_path_test(function));

    // Error case test
    if function.has_error_case() {
        tests.push(generate_error_test(function));
    }

    // Edge case tests
    for param in &function.parameters {
        if param.is_optional {
            tests.push(generate_optional_param_test(function, param));
        }
    }

    tests.join("\n\n")
}

fn generate_happy_path_test(function: &FunctionInfo) -> String {
    let test_name = format!("test_{}_happy_path", function.name.to_snake_case());

    format!(
        r#"
    #[test]
    fn {test_name}() {{
        // Arrange
        {setup}

        // Act
        {call}

        // Assert
        {assertions}
    }}"#,
        test_name = test_name,
        setup = generate_test_setup(function),
        call = generate_function_call(function),
        assertions = generate_assertions(function)
    )
}

fn generate_error_test(function: &FunctionInfo) -> String {
    let test_name = format!("test_{}_error_case", function.name.to_snake_case());

    format!(
        r#"
    #[test]
    fn {test_name}() {{
        // Arrange with invalid input
        {error_setup}

        // Act & Assert
        assert!(result.is_err());
    }}"#,
        test_name = test_name,
        error_setup = generate_error_setup(function)
    )
}

fn generate_optional_param_test(function: &FunctionInfo, param: &Parameter) -> String {
    let test_name = format!(
        "test_{}_without_{}",
        function.name.to_snake_case(),
        param.name.to_snake_case()
    );

    format!(
        r#"
    #[test]
    fn {test_name}() {{
        // Test without optional parameter
        // TODO: Implement test
    }}"#,
        test_name = test_name
    )
}

fn generate_function_call(function: &FunctionInfo) -> String {
    let params: Vec<String> = function.parameters.iter().map(|p| p.name.clone()).collect();
    let call = if function.is_async {
        format!("{}.await", function.name)
    } else {
        format!("{}({})", function.name, params.join(", "))
    };

    let result_binding = if function.return_type.as_ref().map_or(false, |t| !t.is_empty()) {
        "let result = "
    } else {
        ""
    };

    format!("    {}{}", result_binding, call)
}

fn generate_assertions(function: &FunctionInfo) -> String {
    match function.return_type.as_deref() {
        Some(t) if t.contains("Result") => {
            "assert!(result.is_ok());".to_string()
        }
        Some(t) if t.contains("Option") => {
            "assert!(result.is_some());".to_string()
        }
        Some(t) if t.contains("bool") => {
            "assert!(result);".to_string()
        }
        Some(t) if t.contains("Vec") || t.contains("[]") => {
            "assert!(!result.is_empty());".to_string()
        }
        Some(t) if t.contains("String") || t.contains("str") => {
            "assert!(!result.is_empty());".to_string()
        }
        _ => "assert!(true); // TODO: Add proper assertion".to_string(),
    }
}

fn generate_mock_value(param: &Parameter) -> String {
    match param.param_type.as_deref() {
        Some(t) if t.contains("String") => {
            if param.is_optional {
                "None".to_string()
            } else {
                r#""test_string""#.to_string()
            }
        }
        Some(t) if t.contains("i32") || t.contains("i64") || t.contains("u32") || t.contains("u64") => {
            if param.is_optional {
                "None".to_string()
            } else {
                "42".to_string()
            }
        }
        Some(t) if t.contains("f32") || t.contains("f64") => {
            if param.is_optional {
                "None".to_string()
            } else {
                "3.14".to_string()
            }
        }
        Some(t) if t.contains("bool") => {
            if param.is_optional {
                "None".to_string()
            } else {
                "true".to_string()
            }
        }
        Some(t) if t.contains("Vec") => {
            if param.is_optional {
                "None".to_string()
            } else {
                "vec![]".to_string()
            }
        }
        Some(t) if t.contains("Option") => {
            "None".to_string()
        }
        _ => {
            if param.is_optional {
                "None".to_string()
            } else {
                "// TODO: Provide mock value".to_string()
            }
        }
    }
}

fn generate_error_setup(function: &FunctionInfo) -> String {
    // Generate setup that should cause an error
    if let Some(first_param) = function.parameters.first() {
        format!("let {} = {}; // Invalid input", first_param.name, generate_invalid_value(first_param))
    } else {
        "// Arrange with invalid context".to_string()
    }
}

fn generate_invalid_value(param: &Parameter) -> String {
    match param.param_type.as_deref() {
        Some(t) if t.contains("String") => r#""""#.to_string(),
        Some(t) if t.contains("i32") || t.contains("u32") => "-1".to_string(),
        Some(t) if t.contains("u64") => "0".to_string(),
        Some(t) if t.contains("i64") => "i64::MAX".to_string(),
        _ => "unsafe {{ std::mem::zeroed() }}".to_string(),
    }
}

// Extension trait for FunctionInfo
trait FunctionInfoExt {
    fn has_error_case(&self) -> bool;
}

impl FunctionInfoExt for FunctionInfo {
    fn has_error_case(&self) -> bool {
        self.return_type
            .as_ref()
            .map(|t| t.contains("Result") || t.contains("Option"))
            .unwrap_or(false)
    }
}
