//! Vitest-specific test templates for Next.js applications

use lumen_core::ProjectInfo;
use crate::TestFile;

/// Generate Next.js E2E test using Vitest and Playwright
pub fn generate_nextjs_e2e(info: &ProjectInfo) -> TestFile {
    let content = format!(
        r#"//! End-to-end tests for {project}
//!
//! Generated by Lumen v{version}
//!
//! Run with: npx vitest e2e

import {{ test, expect }} from '@playwright/test';

test.describe('{project} Critical Flows', () => {{
    test.beforeEach(async ({{ page }}) => {{
        // TODO: Setup test environment
        // Example: Login, navigate to starting page
        await page.goto('http://localhost:3000');
    }});

    test('should load homepage', async ({{ page }}) => {{
        await expect(page).toHaveTitle(/{project}/i);
    }});

    test('should handle user authentication flow', async ({{ page }}) => {{
        // TODO: Implement authentication test
        // await page.click('text=Login');
        // await page.fill('input[name="email"]', 'test@example.com');
        // await page.fill('input[name="password"]', 'password123');
        // await page.click('button[type="submit"]');
        // await expect(page).toHaveURL(/.*dashboard/);
    }});

    test('should handle main user journey', async ({{ page }}) => {{
        // TODO: Implement complete user journey
        // This should test the most critical path through your application
    }});

    test('should handle error states gracefully', async ({{ page }}) => {{
        // TODO: Test error handling
        // Navigate to invalid URL
        // Verify error page is shown
        // Verify recovery options
    }});

    test('should be accessible', async ({{ page }}) => {{
        // Basic accessibility checks
        await page.click('body');  // Remove focus from any element

        // Check for skip link (accessibility feature)
        const skipLink = page.locator('a[href*="skip"]').first();
        await expect(skipLink).toBeVisible();
    }});
}});
"#,
        project = info.name,
        version = env!("CARGO_PKG_VERSION")
    );

    TestFile {
        path: std::path::PathBuf::from("e2e/critical-flows.spec.ts"),
        content,
        test_type: crate::TestType::E2E,
    }
}

/// Generate component test template for Vitest
pub fn generate_component_test(component_name: &str, file_path: &str) -> String {
    format!(
        r#"// Component tests for {component_name}
//
// Run with: npx vitest {file_path}

import {{ describe, it, expect, vi }} from 'vitest';
import {{ mount }} from '@vue/test-utils';
// OR for React:
import {{ render, screen }} from '@testing-library/react';

describe('{component_name}', () => {{
    // Clean up mocks after each test
    afterEach(() => {{
        vi.restoreAllMocks();
    }});

    it('should render correctly', () => {{
        // TODO: Implement component test
        // const wrapper = mount({component_name});
        // expect(wrapper.exists()).toBe(true);
    }});

    it('should handle user interactions', async () => {{
        // TODO: Test user interactions
        // await wrapper.find('button').trigger('click');
        // expect(wrapper.emitted('some-event')).toBeTruthy();
    }});

    it('should display loading state', () => {{
        // TODO: Test loading state
        // const wrapper = mount({component_name}, {{
        //     propsData: {{ loading: true }}
        // }});
        // expect(wrapper.find('.loader').exists()).toBe(true);
    }});
}});
"#
    )
}
