//! NestJS-specific test templates

use lumenx_core::ProjectInfo;
use crate::TestFile;

/// Generate NestJS E2E test using supertest
pub fn generate_nestjs_e2e(info: &ProjectInfo) -> TestFile {
    let content = format!(
        r#"//! End-to-end tests for {project}
//!
//! Generated by Lumen v{version}
//!
//! Run with: npx jest e2e

import {{ Test, TestingModule }} from '@nestjs/testing';
import {{ INestApplication }} from '@nestjs/common';
import {{ AppModule }} from './../src/app.module';

// Integration test setup
describe('AppController (e2e)', () => {{
    let app: INestApplication;

    beforeAll(async () => {{
        const moduleFixture: TestingModule = await Test.createTestingModule({{
            imports: [AppModule],
        }}).compile();

        app = moduleFixture.createNestApplication();

        // TODO: Add any additional setup
        // await app.init();
    }});

    afterAll(async () => {{
        await app.close();
    }});

    it('/ (GET)', () => {{
        return request(app.getHttpServer())
            .get('/')
            .expect(200)
            .expect('Hello World!');
    }});

    describe('{project} API', () => {{
        // TODO: Add API endpoint tests
        // Example for a users endpoint:
        // describe('/users (GET)', () => {{
        //     it('should return array of users', () => {{
        //         return request(app.getHttpServer())
        //             .get('/users')
        //             .expect(200)
        //             .expect(Array)
        //             .expect(res => {{
        //                 expect(res.body[0].email).toBeDefined();
        //             }});
        //     }});
        // }});

        // Example for authentication:
        // describe('/auth/login (POST)', () => {{
        //     it('should authenticate user with valid credentials', () => {{
        //         return request(app.getHttpServer())
        //             .post('/auth/login')
        //             .send({{
        //                 email: 'test@example.com',
        //                 password: 'password123'
        //             }})
        //             .expect(201)
        //             .expect(res => {{
        //                 expect(res.body.token).toBeDefined();
        //                 expect(res.body.user.email).toBe('test@example.com');
        //             }});
        //     }});
        // }});
    }});
}});

describe('Authentication & Authorization', () => {{
    // TODO: Add authentication tests
    // Test login, logout, token refresh, role-based access
}});

describe('Database Integration', () => {{
    // TODO: Add database integration tests
    // Test CRUD operations with actual database
}});

describe('Error Handling', () => {{
    // TODO: Add error handling tests
    // Test validation errors, 404s, 500s, etc.
}});
"#,
        project = info.name,
        version = env!("CARGO_PKG_VERSION")
    );

    TestFile {
        path: std::path::PathBuf::from("test/app.e2e-spec.ts"),
        content,
        test_type: crate::TestType::E2E,
    }
}

/// Generate NestJS unit test template
pub fn generate_controller_test(controller_name: &str) -> String {
    let file_name = format!("{}.spec.ts", controller_name.to_lowercase().replace("controller", "").trim());
    format!(
        r#"// Unit tests for {controller_name}
//
// Run with: npx jest {file_name}

import {{ Test }} from '@nestjs/testing';
import {{ UsersController }} from './users.controller';
import {{ UsersService }} from './users.service';

describe('{controller_name}', () => {{
    let controller: UsersController;
    let service: UsersService;

    beforeEach(async () => {{
        const module: TestingModule = await Test.createTestingModule({{
            controllers: [UsersController],
            providers: [UsersService],
        }}).compile();

        controller = module.get<UsersController>();
        service = module.get<UsersService>();
    }});

    it('should be defined', () => {{
        expect(controller).toBeDefined();
    }});

    // TODO: Add controller method tests
    // describe('findAll', () => {{
    //     it('should return an array of users', async () => {{
    //         const result = ['test'];
    //         jest.spyOn(service, 'findAll').mockImplementation(async () => result);
    //
    //         expect(await controller.findAll()).toBe(result);
    //     }});
    // }});
}});
"#
    )
}

/// Generate NestJS service test template
pub fn generate_service_test(service_name: &str) -> String {
    let file_name = format!("{}.spec.ts", service_name.to_lowercase().replace("service", "").trim());
    format!(
        r#"// Unit tests for {service_name}
//
// Run with: npx jest {file_name}

import {{ Test }} from '@nestjs/testing';
import {{ getRepositoryToken }} from '@nestjs/typeorm';
import {{ Repository }} from 'typeorm';
import {{ UsersService }} from './users.service';
import {{ User }} from './user.entity';
import {{ NotFoundException }} from '@nestjs/common';

describe('UsersService', () => {{
    let service: UsersService;
    let repository: Repository<User>;

    beforeEach(async () => {{
        const module = await Test.createTestingModule({{
            providers: [
                UsersService,
                {{
                    provide: getRepositoryToken(User),
                    useValue: {{}}, // Mock repository
                }},
            ],
        }}).compile();

        service = module.get<UsersService>(UsersService);
        repository = module.get<Repository<User>>(getRepositoryToken(User));
    }});

    it('should be defined', () => {{
        expect(service).toBeDefined();
    }});

    // TODO: Add service method tests
    // describe('findAll', () => {{
    //     it('should return an array of users', async () => {{
    //         const expectedUsers = [{{ id: 1, name: 'Test' }}];
    //         jest.spyOn(repository, 'find').mockResolvedValue(expectedUsers as any);
    //
    //         const result = await service.findAll();
    //
    //         expect(result).toEqual(expectedUsers);
    //     }});
    // }});
}});
"#
    )
}
